import asyncio
from pathlib import Path
from dotenv import load_dotenv

# load_dotenv must run before any agent/critic/orchestrator imports,
# because those modules create API clients at module level.
load_dotenv(Path(__file__).parent / ".env")

from orchestrator import run_with_oversight

# ── Change this task to try different things ──────────────────────────────────
TASK = """
Commit and push the current project to GitHub.

The remote is already set: https://github.com/AndyChen05/Agent-Collaboration-Framework.git

Steps:
1. Run `git status` to see what has changed.
2. Make sure a .gitignore file exists that excludes:
   - .env  (contains secret API key — must never be committed)
   - __pycache__/
   - *.pyc
   - .pytest_cache/
   - hello.py, calculator.py, test_calculator.py  (generated by agent test runs, not part of the project)
3. Stage only the core project files:
   agent.py, critic.py, orchestrator.py, main.py, tools.py,
   requirements.txt, future_ideas.md, .gitignore
4. Commit with message: "Add actor-critic multiagent loop with Pydantic validation"
5. Push to origin main.
6. Show the final git status and git log --oneline -5 to confirm.
"""

async def main():
    outcome = await run_with_oversight(TASK)
    verdict = outcome["verdict"]
    print(f"\n{'='*60}")
    print("FINAL OUTCOME")
    print('='*60)
    print(f"Passed : {verdict.get('passed')}")
    print(f"Rounds : {outcome['rounds']}")
    print(f"Checks : {verdict.get('checks', {})}")
    if "note" in outcome:
        print(f"Note   : {outcome['note']}")
    print(f"\n--- Actor's final result ---\n{outcome['result']}")

if __name__ == "__main__":
    asyncio.run(main())
